### ISSUE TITLE
IT DOES NOT WORK THE EVENT DRAG THE OBJECT IN A SCENE

### ISSUE THREAD

**Issue by batereylor89** [4ian/GDevelop-website#3]
Hello community Gdevelop

I have a problem making a game , I created several scenes in the game, each of the scenes works perfectly when compiled for separate , but when I compile the whole game and start running scene 4 malfunctioned event drag the object.
When I run the scene 4 if it works.

How can i fix this?.

Thank you

**Comment by 4ian** [comment]
Hey batereylor89,

Your question is welcome, but not here on the GitHub repository which is meant to be used only be developers and for the website of GDevelop. If you want to ask about GDevelop, please send a message on the forum.
Also, please never use capitals to write the title of a question, here or anywhere on the internet. It sounds like you're screaming.
Finally, your problem is quite hard to get : if you ask your question on the forum, please attach a copy of your game file and explain step by step and precisely how to reproduce the issue. 
Thanks :)

**Comment by 4ian** [comment]
I'm closing the issue here ;)

**Comment by batereylor89** [comment]
Thank you very much , I will investigate forum
