### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by steveang9999** [4ian/GDevelop-website#34]
Hi all!

I made a game with GDevelop and I think it would be great to have it on the website in game showcase.

## Screenshots

=> 
[url=https://ibb.co/pKw9HCF][img]https://i.ibb.co/ykPbzLj/Screen-Shot-10-inches-2.png[/img][/url]
[url=https://ibb.co/xs3dS8b][img]https://i.ibb.co/g76hMF8/Screen-Shot-10-inches-3.png[/img][/url]
[url=https://ibb.co/42wh1W6][img]https://i.ibb.co/pQ6Yh2t/Screen-Shot-10-inches-1.png[/img][/url]

## Name, links and details

=> Developed by Rebel Valley Inc.
      Game Name: Eggventure: Savior of Galaxy
      Google Play Store download Link: 
https://play.google.com/store/apps/details?id=rebelvalleyinc.first.eggventure&hl=en

**Comment by 4ian** [comment]
Nice! Will add it on the website. Looks pretty, look forward to try it 👍

**Comment by 4ian** [comment]
I've tested it, it's pretty cool! Love the atmosphere of the game. A few comments:
* Maybe have at the bottom of the screen a semi transparent line of something showing the separation between left/right. Would be useful especially when you're trying to deal with a dangerous obstacle and don't want to press the wrong button :)
* A few buttons are hard to press, you could add a virtual area around the button that is larger so that the button works when this area is touched.
* As this is a game of "die and retry" and needs precision and it's on mobile, I would make the death less punishing by at least making it almost immediate to restart (you show the "you're dead" message then almost immediatly allow the user to play again). Otherwise it's a bit frustrating. Potentially maybe add checkpoints in the middle of a level?

Apart from this, good job, this is really good looking and fun!! :)

**Comment by steveang9999** [comment]
Thanks a lot for the feedback! Hope to see it on the game showcase

**Comment by 4ian** [comment]
Added here: https://gdevelop-app.com/games-showcase/ ;) 
As it's a pretty game, well designed, published on a store and looks polished, I've added it to the top of the page!
