### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by efraingatuzz** [4ian/GDevelop-website#38]
Hi all!

I made a game for Android with GDevelop and I think it would be great to have it on the website.

## Screenshots

![menu](https://user-images.githubusercontent.com/10351492/54015979-c7316300-4181-11e9-85ca-65393967bc2e.png)

![game](https://user-images.githubusercontent.com/10351492/54015991-d31d2500-4181-11e9-97d7-a919e82ffc27.png)

## Name, links and details
The game is Evasion (free version)

This is the link:

[Evasion Free](https://play.google.com/store/apps/details?id=com.evasion.space.free )

You need to avoid the asteroids. How far can you go?

**Comment by PlanetPlay-Studios** [comment]
Hey developer...your google play link does not really go to the playstore.....check on that

**Comment by efraingatuzz** [comment]
Sorry!

I updated the link!

Efrain

**Comment by PlanetPlay-Studios** [comment]
Check on your ads too because they are not showing(it indicates at the plastore that u have ads) ...
And then about the performance of the game....from my view...there might be some loose events that are just running when they should not be or you are having many images moving across screen or may be you are  not destroying the images when out of screen ......

but the simplicity of the game and UI is not bad though

**Comment by 4ian** [comment]
(Finally) added to the website! :)
